package content.region.misthalin.quest.member.asoulbane

import core.api.getAnimation

object ASBUtils {

    val ANIMATION_TOLNA_RIFT_CRAWL = getAnimation(3838)

    const val VARBIT_TOLNA_RIFT_ROPE = 2032
    const val VARBIT_TOLNA_RIFT_WARNING_SIGN = 2034
    const val ATTRIBUTE_TOLNA_RIFT_ACCESS = "tolna-rift-access"

    /*
    const val VARBIT_QUEST_A_SOULS_BANE_PROGRESS = 2011
    const val VARBIT_QUEST_A_SOULS_BANE_FEAR_REAPER_CURRENT_LOCATION = 2012
    const val VARBIT_QUEST_A_SOULS_BANE_FIRST_REAL_CONFUSION_BEAST_KILL = 2014
    const val VARBIT_QUEST_A_SOULS_BANE_SECOND_REAL_CONFUSION_BEAST_KILL = 2015
    const val VARBIT_QUEST_A_SOULS_BANE_THIRD_REAL_CONFUSION_BEAST_KILL = 2016
    const val VARBIT_QUEST_A_SOULS_BANE_FOURTH_REAL_CONFUSION_BEAST_KILL = 2017
    const val VARBIT_QUEST_A_SOULS_BANE_FIFTH_REAL_CONFUSION_BEAST_KILL = 2018
    const val VARBIT_QUEST_A_SOULS_BANE_FEAR_REAPER_KILL_COUNT = 2019
    const val VARBIT_QUEST_A_SOULS_BANE_BOSS_ROOM_UNLOCKED = 2020
    const val VARBIT_QUEST_A_SOULS_BANE_HOPELESS_CREATURE_KILLS = 2021
    const val VARBIT_QUEST_A_SOULS_BANE_EASTERN_TOLNA_HEAD_KILLED = 2022
    const val VARBIT_QUEST_A_SOULS_BANE_SOUTHERN_TOLNA_HEAD_KILLED = 2023
    const val VARBIT_QUEST_A_SOULS_BANE_NORTHERN_TOLNA_HEAD_KILLED = 2024
    const val VARBIT_QUEST_A_SOULS_BANE_SHOW_TOLNA = 2025
    const val VARBIT_QUEST_A_SOULS_BANE_HIDE_LAUNA = 2026
    const val VARBIT_QUEST_A_SOULS_BANE_FEAR_REAPER_LAST_LOCATION = 2027
    const val VARBIT_QUEST_A_SOULS_BANE_FEAR_ROOM_UNLOCKED = 2028
    const val VARBIT_QUEST_A_SOULS_BANE_ANGER_WEAPON_CHOICE = 2029
    const val VARBIT_QUEST_A_SOULS_BANE_CONFUSION_ROOM_UNLOCKED = 2030
    const val VARBIT_QUEST_A_SOULS_BANE_HOPELESS_ROOM_UNLOCKED = 2031
    const val VARBIT_QUEST_A_SOULS_BANE_BOSS_FIGHT_STARTED = 2033

    const val VARBIT_QUEST_A_SOULS_BANE_FEAR_REAPER_SPAWNED = 2035
    const val VARBIT_QUEST_A_SOULS_BANE_ANGER_ROOM_DAMAGE_DEALT = 2036
    const val VARBIT_QUEST_A_SOULS_BANE_CONFUSION_BEAST_ATTACK_COUNT_1 = 2037
    const val VARBIT_QUEST_A_SOULS_BANE_CONFUSION_BEAST_ATTACK_COUNT_2 = 2038
    const val VARBIT_QUEST_A_SOULS_BANE_CONFUSION_BEAST_ATTACK_COUNT_3 = 2039
    const val VARBIT_QUEST_A_SOULS_BANE_CONFUSION_BEAST_ATTACK_COUNT_4 = 2040
    const val VARBIT_QUEST_A_SOULS_BANE_RAGE_LEVEL_REACHED = 2042
    */
}