// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: descriptor.proto

package proto.management;

/**
 * The interface Clan join notification or builder.
 */
public interface ClanJoinNotificationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.ClanJoinNotification)
        com.google.protobuf.MessageOrBuilder {

    /**
     * Has username boolean.
     *
     * @return the boolean
     */
    boolean hasUsername();

    /**
     * Gets username.
     *
     * @return the username
     */
    String getUsername();

    /**
     * Gets username bytes.
     *
     * @return the username bytes
     */
    com.google.protobuf.ByteString
    getUsernameBytes();

    /**
     * Has clan name boolean.
     *
     * @return the boolean
     */
    boolean hasClanName();

    /**
     * Gets clan name.
     *
     * @return the clan name
     */
    String getClanName();

    /**
     * Gets clan name bytes.
     *
     * @return the clan name bytes
     */
    com.google.protobuf.ByteString
    getClanNameBytes();

    /**
     * Has world boolean.
     *
     * @return the boolean
     */
    boolean hasWorld();

    /**
     * Gets world.
     *
     * @return the world
     */
    int getWorld();
}
