// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: descriptor.proto

package proto.management;

/**
 * The interface Request clan info or builder.
 */
public interface RequestClanInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.RequestClanInfo)
        com.google.protobuf.MessageOrBuilder {

    /**
     * Has world boolean.
     *
     * @return the boolean
     */
    boolean hasWorld();

    /**
     * Gets world.
     *
     * @return the world
     */
    int getWorld();

    /**
     * Has clan owner boolean.
     *
     * @return the boolean
     */
    boolean hasClanOwner();

    /**
     * Gets clan owner.
     *
     * @return the clan owner
     */
    String getClanOwner();

    /**
     * Gets clan owner bytes.
     *
     * @return the clan owner bytes
     */
    com.google.protobuf.ByteString
    getClanOwnerBytes();
}
