// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

/**
 * The interface Blocked update or builder.
 */
public interface BlockedUpdateOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.BlockedUpdate)
        com.google.protobuf.MessageOrBuilder {

    /**
     * Has type boolean.
     *
     * @return the boolean
     */
    boolean hasType();

    /**
     * Gets type.
     *
     * @return the type
     */
    BlockedUpdate.Type getType();

    /**
     * Has username boolean.
     *
     * @return the boolean
     */
    boolean hasUsername();

    /**
     * Gets username.
     *
     * @return the username
     */
    String getUsername();

    /**
     * Gets username bytes.
     *
     * @return the username bytes
     */
    com.google.protobuf.ByteString
    getUsernameBytes();

    /**
     * Has friend boolean.
     *
     * @return the boolean
     */
    boolean hasFriend();

    /**
     * Gets friend.
     *
     * @return the friend
     */
    String getFriend();

    /**
     * Gets friend bytes.
     *
     * @return the friend bytes
     */
    com.google.protobuf.ByteString
    getFriendBytes();
}
