// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface ClanLeaveNotificationOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.ClanLeaveNotification)
        com.google.protobuf.MessageOrBuilder {

    boolean hasUsername();

    java.lang.String getUsername();

    com.google.protobuf.ByteString
    getUsernameBytes();

    boolean hasClanName();

    java.lang.String getClanName();

    com.google.protobuf.ByteString
    getClanNameBytes();

    boolean hasWorld();

    int getWorld();
}
