// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface ClanMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.ClanMessage)
        com.google.protobuf.MessageOrBuilder {

    boolean hasSender();

    java.lang.String getSender();

    com.google.protobuf.ByteString
    getSenderBytes();

    boolean hasClanName();

    java.lang.String getClanName();

    com.google.protobuf.ByteString
    getClanNameBytes();

    boolean hasMessage();

    java.lang.String getMessage();

    com.google.protobuf.ByteString
    getMessageBytes();

    boolean hasRank();

    int getRank();
}
