// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface FriendUpdateOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.FriendUpdate)
        com.google.protobuf.MessageOrBuilder {

    boolean hasType();

    proto.management.FriendUpdate.Type getType();

    boolean hasUsername();

    java.lang.String getUsername();

    com.google.protobuf.ByteString
    getUsernameBytes();

    boolean hasFriend();

    java.lang.String getFriend();

    com.google.protobuf.ByteString
    getFriendBytes();
}
