// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface LeaveClanRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.LeaveClanRequest)
        com.google.protobuf.MessageOrBuilder {

    boolean hasUsername();

    java.lang.String getUsername();

    com.google.protobuf.ByteString
    getUsernameBytes();

    boolean hasClanName();

    java.lang.String getClanName();

    com.google.protobuf.ByteString
    getClanNameBytes();
}
