// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface PlayerStatusUpdateOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.PlayerStatusUpdate)
        com.google.protobuf.MessageOrBuilder {

    boolean hasUsername();

    java.lang.String getUsername();

    com.google.protobuf.ByteString
    getUsernameBytes();

    boolean hasWorld();

    int getWorld();

    boolean hasNotifyFriendsOnly();

    boolean getNotifyFriendsOnly();
}
