// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

/**
 * Private message.
 */
public final class PrivateMessage extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:management.PrivateMessage)
        PrivateMessageOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use PrivateMessage.newBuilder() to construct.
    private PrivateMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private PrivateMessage() {
        sender_ = "";
        receiver_ = "";
        message_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
            UnusedPrivateParameter unused) {
        return new PrivateMessage();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private PrivateMessage(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 10: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000001;
                        sender_ = bs;
                        break;
                    }
                    case 18: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000002;
                        receiver_ = bs;
                        break;
                    }
                    case 26: {
                        com.google.protobuf.ByteString bs = input.readBytes();
                        bitField0_ |= 0x00000004;
                        message_ = bs;
                        break;
                    }
                    case 32: {
                        bitField0_ |= 0x00000008;
                        rank_ = input.readInt32();
                        break;
                    }
                    default: {
                        if (!parseUnknownField(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    /**
     * Gets descriptor.
     *
     * @return the descriptor
     */
    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return ManagementProtos.internal_static_management_PrivateMessage_descriptor;
    }

    @Override
    protected FieldAccessorTable
    internalGetFieldAccessorTable() {
        return ManagementProtos.internal_static_management_PrivateMessage_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        PrivateMessage.class, Builder.class);
    }

    private int bitField0_;
    /**
     * The constant SENDER_FIELD_NUMBER.
     */
    public static final int SENDER_FIELD_NUMBER = 1;
    private volatile Object sender_;

    @Override
    public boolean hasSender() {
        return ((bitField0_ & 0x00000001) != 0);
    }

    @Override
    public String getSender() {
        Object ref = sender_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                sender_ = s;
            }
            return s;
        }
    }

    @Override
    public com.google.protobuf.ByteString
    getSenderBytes() {
        Object ref = sender_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            sender_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * The constant RECEIVER_FIELD_NUMBER.
     */
    public static final int RECEIVER_FIELD_NUMBER = 2;
    private volatile Object receiver_;

    @Override
    public boolean hasReceiver() {
        return ((bitField0_ & 0x00000002) != 0);
    }

    @Override
    public String getReceiver() {
        Object ref = receiver_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                receiver_ = s;
            }
            return s;
        }
    }

    @Override
    public com.google.protobuf.ByteString
    getReceiverBytes() {
        Object ref = receiver_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            receiver_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * The constant MESSAGE_FIELD_NUMBER.
     */
    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile Object message_;

    @Override
    public boolean hasMessage() {
        return ((bitField0_ & 0x00000004) != 0);
    }

    @Override
    public String getMessage() {
        Object ref = message_;
        if (ref instanceof String) {
            return (String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
                message_ = s;
            }
            return s;
        }
    }

    @Override
    public com.google.protobuf.ByteString
    getMessageBytes() {
        Object ref = message_;
        if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (String) ref);
            message_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    /**
     * The constant RANK_FIELD_NUMBER.
     */
    public static final int RANK_FIELD_NUMBER = 4;
    private int rank_;

    @Override
    public boolean hasRank() {
        return ((bitField0_ & 0x00000008) != 0);
    }

    @Override
    public int getRank() {
        return rank_;
    }

    private byte memoizedIsInitialized = -1;

    @Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasSender()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasReceiver()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasMessage()) {
            memoizedIsInitialized = 0;
            return false;
        }
        if (!hasRank()) {
            memoizedIsInitialized = 0;
            return false;
        }
        memoizedIsInitialized = 1;
        return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sender_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, receiver_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
            output.writeInt32(4, rank_);
        }
        unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sender_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, receiver_);
        }
        if (((bitField0_ & 0x00000004) != 0)) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
        }
        if (((bitField0_ & 0x00000008) != 0)) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt32Size(4, rank_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @Override
    public boolean equals(final Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof PrivateMessage)) {
            return super.equals(obj);
        }
        PrivateMessage other = (PrivateMessage) obj;

        if (hasSender() != other.hasSender()) return false;
        if (hasSender()) {
            if (!getSender()
                    .equals(other.getSender())) return false;
        }
        if (hasReceiver() != other.hasReceiver()) return false;
        if (hasReceiver()) {
            if (!getReceiver()
                    .equals(other.getReceiver())) return false;
        }
        if (hasMessage() != other.hasMessage()) return false;
        if (hasMessage()) {
            if (!getMessage()
                    .equals(other.getMessage())) return false;
        }
        if (hasRank() != other.hasRank()) return false;
        if (hasRank()) {
            if (getRank()
                    != other.getRank()) return false;
        }
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
    }

    @Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasSender()) {
            hash = (37 * hash) + SENDER_FIELD_NUMBER;
            hash = (53 * hash) + getSender().hashCode();
        }
        if (hasReceiver()) {
            hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
            hash = (53 * hash) + getReceiver().hashCode();
        }
        if (hasMessage()) {
            hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
            hash = (53 * hash) + getMessage().hashCode();
        }
        if (hasRank()) {
            hash = (37 * hash) + RANK_FIELD_NUMBER;
            hash = (53 * hash) + getRank();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    /**
     * Parse from private message.
     *
     * @param data the data
     * @return the private message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static PrivateMessage parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from private message.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the private message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static PrivateMessage parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from private message.
     *
     * @param data the data
     * @return the private message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static PrivateMessage parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from private message.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the private message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static PrivateMessage parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from private message.
     *
     * @param data the data
     * @return the private message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static PrivateMessage parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    /**
     * Parse from private message.
     *
     * @param data              the data
     * @param extensionRegistry the extension registry
     * @return the private message
     * @throws InvalidProtocolBufferException the invalid protocol buffer exception
     */
    public static PrivateMessage parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    /**
     * Parse from private message.
     *
     * @param input the input
     * @return the private message
     * @throws IOException the io exception
     */
    public static PrivateMessage parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    /**
     * Parse from private message.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the private message
     * @throws IOException the io exception
     */
    public static PrivateMessage parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * Parse delimited from private message.
     *
     * @param input the input
     * @return the private message
     * @throws IOException the io exception
     */
    public static PrivateMessage parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    /**
     * Parse delimited from private message.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the private message
     * @throws IOException the io exception
     */
    public static PrivateMessage parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    /**
     * Parse from private message.
     *
     * @param input the input
     * @return the private message
     * @throws IOException the io exception
     */
    public static PrivateMessage parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    /**
     * Parse from private message.
     *
     * @param input             the input
     * @param extensionRegistry the extension registry
     * @return the private message
     * @throws IOException the io exception
     */
    public static PrivateMessage parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() {
        return newBuilder();
    }

    /**
     * New builder builder.
     *
     * @return the builder
     */
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    /**
     * New builder builder.
     *
     * @param prototype the prototype
     * @return the builder
     */
    public static Builder newBuilder(PrivateMessage prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    @Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
            BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Builder.
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:management.PrivateMessage)
            PrivateMessageOrBuilder {
        /**
         * Gets descriptor.
         *
         * @return the descriptor
         */
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return ManagementProtos.internal_static_management_PrivateMessage_descriptor;
        }

        @Override
        protected FieldAccessorTable
        internalGetFieldAccessorTable() {
            return ManagementProtos.internal_static_management_PrivateMessage_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            PrivateMessage.class, Builder.class);
        }

        // Construct using proto.management.PrivateMessage.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        @Override
        public Builder clear() {
            super.clear();
            sender_ = "";
            bitField0_ = (bitField0_ & ~0x00000001);
            receiver_ = "";
            bitField0_ = (bitField0_ & ~0x00000002);
            message_ = "";
            bitField0_ = (bitField0_ & ~0x00000004);
            rank_ = 0;
            bitField0_ = (bitField0_ & ~0x00000008);
            return this;
        }

        @Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return ManagementProtos.internal_static_management_PrivateMessage_descriptor;
        }

        @Override
        public PrivateMessage getDefaultInstanceForType() {
            return PrivateMessage.getDefaultInstance();
        }

        @Override
        public PrivateMessage build() {
            PrivateMessage result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @Override
        public PrivateMessage buildPartial() {
            PrivateMessage result = new PrivateMessage(this);
            int from_bitField0_ = bitField0_;
            int to_bitField0_ = 0;
            if (((from_bitField0_ & 0x00000001) != 0)) {
                to_bitField0_ |= 0x00000001;
            }
            result.sender_ = sender_;
            if (((from_bitField0_ & 0x00000002) != 0)) {
                to_bitField0_ |= 0x00000002;
            }
            result.receiver_ = receiver_;
            if (((from_bitField0_ & 0x00000004) != 0)) {
                to_bitField0_ |= 0x00000004;
            }
            result.message_ = message_;
            if (((from_bitField0_ & 0x00000008) != 0)) {
                result.rank_ = rank_;
                to_bitField0_ |= 0x00000008;
            }
            result.bitField0_ = to_bitField0_;
            onBuilt();
            return result;
        }

        @Override
        public Builder clone() {
            return super.clone();
        }

        @Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.setField(field, value);
        }

        @Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        @Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        @Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, Object value) {
            return super.setRepeatedField(field, index, value);
        }

        @Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                Object value) {
            return super.addRepeatedField(field, value);
        }

        @Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof PrivateMessage) {
                return mergeFrom((PrivateMessage) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        /**
         * Merge from builder.
         *
         * @param other the other
         * @return the builder
         */
        public Builder mergeFrom(PrivateMessage other) {
            if (other == PrivateMessage.getDefaultInstance()) return this;
            if (other.hasSender()) {
                bitField0_ |= 0x00000001;
                sender_ = other.sender_;
                onChanged();
            }
            if (other.hasReceiver()) {
                bitField0_ |= 0x00000002;
                receiver_ = other.receiver_;
                onChanged();
            }
            if (other.hasMessage()) {
                bitField0_ |= 0x00000004;
                message_ = other.message_;
                onChanged();
            }
            if (other.hasRank()) {
                setRank(other.getRank());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @Override
        public final boolean isInitialized() {
            if (!hasSender()) {
                return false;
            }
            if (!hasReceiver()) {
                return false;
            }
            if (!hasMessage()) {
                return false;
            }
            if (!hasRank()) {
                return false;
            }
            return true;
        }

        @Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            PrivateMessage parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (PrivateMessage) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private int bitField0_;

        private Object sender_ = "";

        public boolean hasSender() {
            return ((bitField0_ & 0x00000001) != 0);
        }

        public String getSender() {
            Object ref = sender_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    sender_ = s;
                }
                return s;
            } else {
                return (String) ref;
            }
        }

        public com.google.protobuf.ByteString
        getSenderBytes() {
            Object ref = sender_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                sender_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * Sets sender.
         *
         * @param value the value
         * @return the sender
         */
        public Builder setSender(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            sender_ = value;
            onChanged();
            return this;
        }

        /**
         * Clear sender builder.
         *
         * @return the builder
         */
        public Builder clearSender() {
            bitField0_ = (bitField0_ & ~0x00000001);
            sender_ = getDefaultInstance().getSender();
            onChanged();
            return this;
        }

        /**
         * Sets sender bytes.
         *
         * @param value the value
         * @return the sender bytes
         */
        public Builder setSenderBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000001;
            sender_ = value;
            onChanged();
            return this;
        }

        private Object receiver_ = "";

        public boolean hasReceiver() {
            return ((bitField0_ & 0x00000002) != 0);
        }

        public String getReceiver() {
            Object ref = receiver_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    receiver_ = s;
                }
                return s;
            } else {
                return (String) ref;
            }
        }

        public com.google.protobuf.ByteString
        getReceiverBytes() {
            Object ref = receiver_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                receiver_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * Sets receiver.
         *
         * @param value the value
         * @return the receiver
         */
        public Builder setReceiver(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            receiver_ = value;
            onChanged();
            return this;
        }

        /**
         * Clear receiver builder.
         *
         * @return the builder
         */
        public Builder clearReceiver() {
            bitField0_ = (bitField0_ & ~0x00000002);
            receiver_ = getDefaultInstance().getReceiver();
            onChanged();
            return this;
        }

        /**
         * Sets receiver bytes.
         *
         * @param value the value
         * @return the receiver bytes
         */
        public Builder setReceiverBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000002;
            receiver_ = value;
            onChanged();
            return this;
        }

        private Object message_ = "";

        public boolean hasMessage() {
            return ((bitField0_ & 0x00000004) != 0);
        }

        public String getMessage() {
            Object ref = message_;
            if (!(ref instanceof String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    message_ = s;
                }
                return s;
            } else {
                return (String) ref;
            }
        }

        public com.google.protobuf.ByteString
        getMessageBytes() {
            Object ref = message_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (String) ref);
                message_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * Sets message.
         *
         * @param value the value
         * @return the message
         */
        public Builder setMessage(
                String value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000004;
            message_ = value;
            onChanged();
            return this;
        }

        /**
         * Clear message builder.
         *
         * @return the builder
         */
        public Builder clearMessage() {
            bitField0_ = (bitField0_ & ~0x00000004);
            message_ = getDefaultInstance().getMessage();
            onChanged();
            return this;
        }

        /**
         * Sets message bytes.
         *
         * @param value the value
         * @return the message bytes
         */
        public Builder setMessageBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            bitField0_ |= 0x00000004;
            message_ = value;
            onChanged();
            return this;
        }

        private int rank_;

        @Override
        public boolean hasRank() {
            return ((bitField0_ & 0x00000008) != 0);
        }

        @Override
        public int getRank() {
            return rank_;
        }

        /**
         * Sets rank.
         *
         * @param value the value
         * @return the rank
         */
        public Builder setRank(int value) {
            bitField0_ |= 0x00000008;
            rank_ = value;
            onChanged();
            return this;
        }

        /**
         * Clear rank builder.
         *
         * @return the builder
         */
        public Builder clearRank() {
            bitField0_ = (bitField0_ & ~0x00000008);
            rank_ = 0;
            onChanged();
            return this;
        }

        @Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFields(unknownFields);
        }

        @Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:management.PrivateMessage)
    }

    // @@protoc_insertion_point(class_scope:management.PrivateMessage)
    private static final PrivateMessage DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new PrivateMessage();
    }

    /**
     * Gets default instance.
     *
     * @return the default instance
     */
    public static PrivateMessage getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    /**
     * The constant PARSER.
     */
    @Deprecated
    public static final com.google.protobuf.Parser<PrivateMessage>
            PARSER = new com.google.protobuf.AbstractParser<PrivateMessage>() {
        @Override
        public PrivateMessage parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new PrivateMessage(input, extensionRegistry);
        }
    };

    /**
     * Parser com . google . protobuf . parser.
     *
     * @return the com . google . protobuf . parser
     */
    public static com.google.protobuf.Parser<PrivateMessage> parser() {
        return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<PrivateMessage> getParserForType() {
        return PARSER;
    }

    @Override
    public PrivateMessage getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

