// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface PrivateMessageOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.PrivateMessage)
        com.google.protobuf.MessageOrBuilder {

    boolean hasSender();

    java.lang.String getSender();

    com.google.protobuf.ByteString
    getSenderBytes();

    boolean hasReceiver();

    java.lang.String getReceiver();

    com.google.protobuf.ByteString
    getReceiverBytes();

    boolean hasMessage();

    java.lang.String getMessage();

    com.google.protobuf.ByteString
    getMessageBytes();

    boolean hasRank();

    int getRank();
}
