// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface RequestClanInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.RequestClanInfo)
        com.google.protobuf.MessageOrBuilder {

    boolean hasWorld();

    int getWorld();

    boolean hasClanOwner();

    java.lang.String getClanOwner();

    com.google.protobuf.ByteString
    getClanOwnerBytes();
}
