// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface SendContactInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.SendContactInfo)
        com.google.protobuf.MessageOrBuilder {

    boolean hasUsername();

    java.lang.String getUsername();

    com.google.protobuf.ByteString
    getUsernameBytes();

    java.util.List<proto.management.SendContactInfo.Contact>
    getContactsList();

    proto.management.SendContactInfo.Contact getContacts(int index);

    int getContactsCount();

    java.util.List<? extends proto.management.SendContactInfo.ContactOrBuilder>
    getContactsOrBuilderList();

    proto.management.SendContactInfo.ContactOrBuilder getContactsOrBuilder(
            int index);

    java.util.List<java.lang.String>
    getBlockedList();

    int getBlockedCount();

    java.lang.String getBlocked(int index);

    com.google.protobuf.ByteString
    getBlockedBytes(int index);
}
