// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Management.proto

package proto.management;

public interface SendClanInfoOrBuilder extends
        // @@protoc_insertion_point(interface_extends:management.SendClanInfo)
        com.google.protobuf.MessageOrBuilder {

    boolean hasClanOwner();

    java.lang.String getClanOwner();

    com.google.protobuf.ByteString
    getClanOwnerBytes();

    boolean hasHasInfo();

    boolean getHasInfo();

    boolean hasClanName();

    java.lang.String getClanName();

    com.google.protobuf.ByteString
    getClanNameBytes();

    boolean hasJoinRequirement();

    int getJoinRequirement();

    boolean hasKickRequirement();

    int getKickRequirement();

    boolean hasMessageRequirement();

    int getMessageRequirement();

    boolean hasLootRequirement();

    int getLootRequirement();

    java.util.List<proto.management.SendClanInfo.ClanMember>
    getMembersList();

    proto.management.SendClanInfo.ClanMember getMembers(int index);

    int getMembersCount();

    java.util.List<? extends proto.management.SendClanInfo.ClanMemberOrBuilder>
    getMembersOrBuilderList();

    proto.management.SendClanInfo.ClanMemberOrBuilder getMembersOrBuilder(
            int index);
}
